# coding: utf-8

"""
    Veem API

    Veem REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: dev@veem.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import client
from client.api.account_controller_api import AccountControllerApi  # noqa: E501
from client.rest import ApiException


class TestAccountControllerApi(unittest.TestCase):
    """AccountControllerApi unit test stubs"""

    def setUp(self):
        self.api = client.api.account_controller_api.AccountControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_contact_using_post(self):
        """Test case for create_contact_using_post

        createContactInBatch  # noqa: E501
        """
        pass

    def test_create_contact_using_post1(self):
        """Test case for create_contact_using_post1

        createContact  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
