# coding: utf-8

"""
    Veem API

    Veem REST API  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: dev@veem.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from client.models.align_monetary_amount import AlignMonetaryAmount  # noqa: F401,E501


class PushPaymentInfoResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'AlignMonetaryAmount',
        'push_payment_info': 'str',
        'reference': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'push_payment_info': 'pushPaymentInfo',
        'reference': 'reference'
    }

    def __init__(self, amount=None, push_payment_info=None, reference=None):  # noqa: E501
        """PushPaymentInfoResponse - a model defined in Swagger"""  # noqa: E501

        self._amount = None
        self._push_payment_info = None
        self._reference = None
        self.discriminator = None

        if amount is not None:
            self.amount = amount
        if push_payment_info is not None:
            self.push_payment_info = push_payment_info
        if reference is not None:
            self.reference = reference

    @property
    def amount(self):
        """Gets the amount of this PushPaymentInfoResponse.  # noqa: E501


        :return: The amount of this PushPaymentInfoResponse.  # noqa: E501
        :rtype: AlignMonetaryAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this PushPaymentInfoResponse.


        :param amount: The amount of this PushPaymentInfoResponse.  # noqa: E501
        :type: AlignMonetaryAmount
        """

        self._amount = amount

    @property
    def push_payment_info(self):
        """Gets the push_payment_info of this PushPaymentInfoResponse.  # noqa: E501


        :return: The push_payment_info of this PushPaymentInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._push_payment_info

    @push_payment_info.setter
    def push_payment_info(self, push_payment_info):
        """Sets the push_payment_info of this PushPaymentInfoResponse.


        :param push_payment_info: The push_payment_info of this PushPaymentInfoResponse.  # noqa: E501
        :type: str
        """
        allowed_values = ["AU", "GB", "MX", "PH", "EU_COMMON"]  # noqa: E501
        if push_payment_info not in allowed_values:
            raise ValueError(
                "Invalid value for `push_payment_info` ({0}), must be one of {1}"  # noqa: E501
                .format(push_payment_info, allowed_values)
            )

        self._push_payment_info = push_payment_info

    @property
    def reference(self):
        """Gets the reference of this PushPaymentInfoResponse.  # noqa: E501


        :return: The reference of this PushPaymentInfoResponse.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this PushPaymentInfoResponse.


        :param reference: The reference of this PushPaymentInfoResponse.  # noqa: E501
        :type: str
        """

        self._reference = reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PushPaymentInfoResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
